[build]
  command = "pnpm run build"
  publish = ".output/public"

[build.environment]
  NODE_VERSION = "22"
  PNPM_VERSION = "10.18.3"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  force = true

[functions]
  directory = ".output/server"
  node_bundler = "none"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
