[build]
  command = "pnpm run build"

[build.environment]
  NODE_VERSION = "22"
  PNPM_VERSION = "10.18.3"
  # Provide minimal env vars for build
  DATABASE_URL = "postgresql://placeholder:placeholder@localhost:5432/placeholder"
  JWT_SECRET = "placeholder-build-only"
  GMAIL_USER = "placeholder@example.com"
  GMAIL_APP_PASSWORD = "placeholder"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
