CREATE TABLE "contact_messages" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"name" varchar(100) NOT NULL,
	"email" varchar(255) NOT NULL,
	"phone" varchar(20),
	"subject" varchar(255) NOT NULL,
	"message" text NOT NULL,
	"accepts_contact" boolean DEFAULT false NOT NULL,
	"status" varchar(50) DEFAULT 'new' NOT NULL,
	"replied_at" timestamp,
	"replied_by" varchar(255),
	"reply_notes" text
);
--> statement-breakpoint
CREATE TABLE "donations" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"email" varchar(255) NOT NULL,
	"first_name" varchar(100),
	"last_name" varchar(100),
	"amount" numeric(10, 2) NOT NULL,
	"currency" varchar(3) DEFAULT 'EUR' NOT NULL,
	"payment_method" varchar(50),
	"stripe_payment_intent_id" varchar(255),
	"stripe_customer_id" varchar(255),
	"status" varchar(50) DEFAULT 'pending' NOT NULL,
	"completed_at" timestamp,
	"receipt_sent" boolean DEFAULT false NOT NULL,
	"receipt_sent_at" timestamp,
	"accepts_newsletter" boolean DEFAULT false NOT NULL,
	"message" text
);
--> statement-breakpoint
CREATE TABLE "downloads" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"file_name" varchar(255) NOT NULL,
	"file_type" varchar(50) NOT NULL,
	"ip_address" varchar(45),
	"user_agent" text,
	"country_code" varchar(2),
	"city" varchar(100)
);
--> statement-breakpoint
CREATE TABLE "incidents" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"incident_date" varchar(10) NOT NULL,
	"incident_time" varchar(5),
	"incident_type" varchar(100) NOT NULL,
	"bus_line" varchar(50),
	"description" text NOT NULL,
	"consequence" varchar(100),
	"consequence_details" text,
	"taxi_cost" numeric(10, 2),
	"email" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "members" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"civility" varchar(10) NOT NULL,
	"first_name" varchar(100) NOT NULL,
	"last_name" varchar(100) NOT NULL,
	"birth_date" varchar(10),
	"email" varchar(255) NOT NULL,
	"phone" varchar(20),
	"address" text NOT NULL,
	"postal_code" varchar(10) NOT NULL,
	"city" varchar(100) NOT NULL,
	"user_type" varchar(50) NOT NULL,
	"school_name" varchar(255),
	"school_section" varchar(255),
	"usage_before" varchar(50),
	"usage_after" varchar(50),
	"membership_fee" numeric(10, 2) NOT NULL,
	"membership_type" varchar(50) NOT NULL,
	"membership_status" varchar(50) DEFAULT 'pending' NOT NULL,
	"membership_start_date" timestamp,
	"membership_end_date" timestamp,
	"payment_method" varchar(50),
	"stripe_customer_id" varchar(255),
	"wants_to_participate" boolean DEFAULT false NOT NULL,
	"participation_areas" json,
	"accepts_newsletter" boolean DEFAULT false NOT NULL,
	"accepts_testimony_publication" boolean DEFAULT false NOT NULL,
	"accepts_media_contact" boolean DEFAULT false NOT NULL,
	"accepts_action_solicitation" boolean DEFAULT false NOT NULL,
	"is_admin" boolean DEFAULT false NOT NULL,
	"notes" text,
	CONSTRAINT "members_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "news" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"title" varchar(255) NOT NULL,
	"slug" varchar(255) NOT NULL,
	"excerpt" text,
	"content" text NOT NULL,
	"cover_image_url" text,
	"author_id" uuid,
	"is_published" boolean DEFAULT false NOT NULL,
	"published_at" timestamp,
	"meta_title" varchar(255),
	"meta_description" text,
	"views_count" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "news_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "newsletter_subscribers" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"email" varchar(255) NOT NULL,
	"first_name" varchar(100),
	"last_name" varchar(100),
	"is_active" boolean DEFAULT true NOT NULL,
	"unsubscribed_at" timestamp,
	"source" varchar(50) NOT NULL,
	CONSTRAINT "newsletter_subscribers_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "subscriptions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"email" varchar(255) NOT NULL,
	"first_name" varchar(100),
	"last_name" varchar(100),
	"amount" numeric(10, 2) NOT NULL,
	"currency" varchar(3) DEFAULT 'EUR' NOT NULL,
	"billing_day" integer NOT NULL,
	"stripe_subscription_id" varchar(255) NOT NULL,
	"stripe_customer_id" varchar(255) NOT NULL,
	"status" varchar(50) DEFAULT 'active' NOT NULL,
	"start_date" timestamp NOT NULL,
	"end_date" timestamp,
	"cancel_at_period_end" boolean DEFAULT false NOT NULL,
	"accepts_newsletter" boolean DEFAULT false NOT NULL,
	CONSTRAINT "subscriptions_stripe_subscription_id_unique" UNIQUE("stripe_subscription_id")
);
--> statement-breakpoint
CREATE TABLE "testimonies" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"first_name" varchar(100) NOT NULL,
	"last_name" varchar(100),
	"email" varchar(255) NOT NULL,
	"phone" varchar(20),
	"city" varchar(100) NOT NULL,
	"age_range" varchar(50) NOT NULL,
	"user_type" varchar(50) NOT NULL,
	"school_name" varchar(255),
	"school_section" varchar(255),
	"workplace" varchar(255),
	"work_hours" varchar(255),
	"usage_before_frequency" varchar(50),
	"usage_before_time" integer,
	"usage_before_destination" text,
	"usage_before_cost" numeric(10, 2),
	"usage_after_solution" varchar(50),
	"usage_after_time" integer,
	"usage_after_correspondences" integer,
	"usage_after_wait_time" integer,
	"usage_after_cost" numeric(10, 2),
	"usage_after_distance" numeric(10, 2),
	"problems" json,
	"missed_correspondences_per_month" integer,
	"testimony_text" text NOT NULL,
	"concrete_example" text,
	"publication_preference" varchar(50) NOT NULL,
	"accepts_site_publication" boolean DEFAULT false NOT NULL,
	"accepts_legal_use" boolean DEFAULT false NOT NULL,
	"accepts_association_contact" boolean DEFAULT false NOT NULL,
	"accepts_media_contact" boolean DEFAULT false NOT NULL,
	"accepts_oral_testimony" boolean DEFAULT false NOT NULL,
	"photo_url" text,
	"moderation_status" varchar(50) DEFAULT 'pending' NOT NULL,
	"moderation_notes" text,
	"moderated_by" varchar(255),
	"moderated_at" timestamp,
	"views_count" integer DEFAULT 0 NOT NULL,
	"reactions_count" integer DEFAULT 0 NOT NULL,
	"shares_count" integer DEFAULT 0 NOT NULL,
	"is_published" boolean DEFAULT false NOT NULL,
	"is_featured" boolean DEFAULT false NOT NULL
);
